version: '3'

networks:
  traefik-proxy:
    driver: bridge

services:
  traefik:
    container_name: traefik
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "--api.insecure=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"

      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.watch=true"
      - "--providers.file.filename=/etc/traefik/dynamic-traefik.toml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=traefik_traefik-proxy"
    networks:
      - traefik-proxy